<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="corner_width" value="0.08" />
  <xacro:property name="corner_joint_offset" value="0.04" />

  <xacro:property name="edge_width" value="0.06" />
  <xacro:property name="edge_length" value="0.30" />

  <xacro:property name="edge_joint_offset" value="0.03" />
  <xacro:property name="edge_joint_y_offset" value="0.15" />

  <xacro:property name="corner_mass" value="0.25"/>
  <xacro:property name="edge_mass" value="0.28"/>

  <xacro:macro name="cs_gz_ref" params="prefix id">
    <gazebo reference="${prefix}/${id}">
      <material>Gazebo/WoodPallet</material>
      <selfCollide>true</selfCollide>
      <gravity>true</gravity>
      <mu1>0.80</mu1>
      <mu2>1.90</mu2>
    </gazebo>
  </xacro:macro>
  

  <!--
    Macro for definition of a construction object corner cube.
    NOTE: parent to world links must be defined outside of these macros! all other links here are child links.
    Corner blocks can connect to at most two children!
  -->
  <xacro:macro name="cs_corner_2children" params="prefix id child1_id child2_id xyz rpy">

    <!-- create the definition for the block -->
    <link name="${prefix}/${id}">
      <inertial>
        <mass value="${corner_mass}" />
        <inertia
          ixx="0.0012" ixy="0"   ixz="0"
                  iyy="0.0012"   iyz="0"
                  izz="0.0012" />
      </inertial>
      <visual>
        <geometry>
          <box size="${corner_width} ${corner_width} ${corner_width}"/>
        </geometry>
        <material name="cs_dark">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${corner_width} ${corner_width} ${corner_width}"/>
        </geometry>
      </collision>
    </link>

    <xacro:cs_gz_ref prefix="${prefix}" id="${id}" />

    <xacro:if value="true">
      <joint name="${prefix}/cs_${id}_${child1_id}" type="revolute">
        <parent link="${prefix}/${id}"/>
        <child link="${prefix}/${child1_id}"/>
        <origin xyz="${corner_joint_offset} ${corner_joint_offset} ${corner_joint_offset}"
          rpy="0 0 0"/>
        <limit effort="30" velocity="0.0" lower="-0.01" upper="0.01" />
      </joint>
    </xacro:if>
    <xacro:if value="true">
      <joint name="${prefix}/cs_${id}_${child2_id}" type="revolute">
        <parent link="${prefix}/${id}"/>
        <child link="${prefix}/${child2_id}"/>
        <origin xyz="${corner_joint_offset} ${-1*corner_joint_offset} ${corner_joint_offset}"
          rpy="0 0 ${PI}"/>
        <limit effort="30" velocity="0.0" lower="-0.01" upper="0.01" />
      </joint>
    </xacro:if>
  </xacro:macro>


  <xacro:macro name="cs_corner_1child" params="prefix id child1_id xyz rpy">

    <!-- create the definition for the block -->
    <link name="${prefix}/${id}">
      <inertial>
        <mass value="${corner_mass}" />
        <inertia
          ixx="0.0012" ixy="0"   ixz="0"
                  iyy="0.0012"   iyz="0"
                  izz="0.0012" />
      </inertial>
      <visual>
        <geometry>
          <box size="${corner_width} ${corner_width} ${corner_width}"/>
        </geometry>
        <material name="cs_dark">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${corner_width} ${corner_width} ${corner_width}"/>
        </geometry>
      </collision>
    </link>

    <xacro:cs_gz_ref prefix="${prefix}" id="${id}" />

    <xacro:if value="true">
      <joint name="${prefix}/cs_${id}_${child1_id}" type="revolute">
        <parent link="${prefix}/${id}"/>
        <child link="${prefix}/${child1_id}"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <limit effort="30" velocity="0.0" lower="-0.01" upper="0.01" />
      </joint>
    </xacro:if>
  </xacro:macro>


  <xacro:macro name="cs_corner" params="prefix id">

    <!-- create the definition for the block -->
    <link name="${prefix}/${id}">
      <inertial>
        <mass value="${corner_mass}" />
        <inertia
          ixx="0.0012" ixy="0"   ixz="0"
                  iyy="0.0012"   iyz="0"
                  izz="0.0012" />
      </inertial>
      <visual>
        <geometry>
          <box size="${corner_width} ${corner_width} ${corner_width}"/>
        </geometry>
        <material name="cs_dark">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${corner_width} ${corner_width} ${corner_width}"/>
        </geometry>
      </collision>
    </link>

    <xacro:cs_gz_ref prefix="${prefix}" id="${id}" />

  </xacro:macro>

  <!--
    Macro for definition of an edge bar of a construction object.
    Bars can only connect to one other object.
    NOTE: because xacro:if doesn't really work in macros, this is duplicated.
  -->
  <xacro:macro name="cs_edge_child" params="prefix id child_id xyz rpy">

    <!-- create the definition for the edge bar -->
    <link name="${prefix}/${id}">
      <inertial>
        <mass value="${edge_mass}" />
        <inertia
          ixx="0.0012" ixy="0"   ixz="0"
                  iyy="0.0012"   iyz="0"
                  izz="0.0012" />
      </inertial>
      <visual>
        <geometry>
          <box size="${edge_width} ${edge_length} ${edge_width}"/>
        </geometry>
        <material name="cs_grey">
          <color rgba="0.7 0.7 0.7 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${edge_width} ${edge_length} ${edge_width}"/>
        </geometry>
      </collision>
    </link>

    <xacro:cs_gz_ref prefix="${prefix}" id="${id}" />

    <xacro:if value="true">
      <joint name="${prefix}/cs_${id}_${child_id}" type="revolute">
        <parent link="${prefix}/${id}"/>
        <child link="${prefix}/${child_id}"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <limit effort="30" velocity="0.0" lower="-0.01" upper="0.01" />
      </joint>
    </xacro:if>
  </xacro:macro>


  <!--
    Macro for definition of an edge bar of a construction object.
    Bars can only connect to one other object.
    NOTE: because xacro:if doesn't really work in macros, this is duplicated.
  -->
  <xacro:macro name="cs_edge" params="prefix id">

    <!-- create the definition for the edge bar -->
    <link name="${prefix}/${id}">
      <inertial>
        <mass value="${edge_mass}" />
        <inertia
          ixx="0.0012" ixy="0"   ixz="0"
                  iyy="0.0012"   iyz="0"
                  izz="0.0012" />
      </inertial>
      <visual>
        <geometry>
          <box size="${edge_width} ${edge_length} ${edge_width}"/>
        </geometry>
        <material name="cs_grey">
          <color rgba="0.7 0.7 0.7 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${edge_width} ${edge_length} ${edge_width}"/>
        </geometry>
      </collision>
    </link>

    <xacro:cs_gz_ref prefix="${prefix}" id="${id}" />

  </xacro:macro>

</robot>
