#note: absolute max joint velocity: 2.0 rad/s
#note: safe joint velocity: 0.5 rad/s
joint_limits:
  wam/shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  wam/wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  wam/wrist_yaw_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  wam/shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  wam/palm_yaw_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  wam/elbow_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  wam/base_yaw_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.1
