#note: absolute max joint velocity: 2.0 rad/s
#note: safe joint velocity: 0.5 rad/s
joint_limits:
  wam2/base_yaw_joint:
    max_velocity: 1.0
    max_acceleration: 1.5
  wam2/shoulder_pitch_joint:
    max_velocity: 1.0
    max_acceleration: 1.5
  wam2/shoulder_yaw_joint:
    max_velocity: 1.0
    max_acceleration: 1.5
  wam2/elbow_pitch_joint:
    max_velocity: 1.0
    max_acceleration: 1.5
  wam2/wrist_yaw_joint:
    max_velocity: 1.0
    max_acceleration: 1.5
  wam2/wrist_pitch_joint:
    max_velocity: 1.0
    max_acceleration: 1.5
  wam2/palm_yaw_joint:
    max_velocity: 1.0
    max_acceleration: 1.5

joint_limits:
  wam2/base_yaw_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
  wam2/shoulder_pitch_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
  wam2/shoulder_yaw_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
  wam2/elbow_pitch_joint:
    has_velocity_limits: true
    has_acceleration_limits: true 
  wam2/wrist_yaw_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
  wam2/wrist_pitch_joint:
    has_velocity_limits: true
    has_acceleration_limits: true 
  wam2/palm_yaw_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
