# action using something stored on predicator
# actual actions performed by other things

# define the goal
string id # robot to move
float64 secs  # time to act
float64 tolerance # how close we need to be to consider it a success
---
# define the result
collab_msgs/Info result
---
# define the feedback message
byte step
byte STARTING=0
byte RETRIEVING_PARAMS=1
byte MOVING=2
byte CONFIRMING=3
